# Herkenning van handgeschreven cijfers met Deep Learning 2

## Convolutionele Neurale Netwerken

Stijn Oomes

donderdag 11 februari 2020

## Importeer libraries

In [405]:
import matplotlib.pyplot as plt
from keras import models
from keras.datasets import mnist
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from keras.utils import to_categorical


## Verover de data

In [406]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [407]:
train_images.shape

(60000, 28, 28)

In [408]:
print(train_labels)

[5 0 4 ... 5 6 8]


In [409]:
train_labels.shape

(60000,)

## Prepareer de images

In [410]:
train_images.shape

(60000, 28, 28)

Normaliseer de images!

In [411]:
train_images_normalized = train_images.astype('float32')/255

In [412]:
train_images_enhanced = train_images_normalized.reshape(60000,28,28,1)

In [413]:
train_images_enhanced.shape

(60000, 28, 28, 1)

In [414]:
test_images_normalized = test_images.astype('float32')/255
test_images_enhanced = test_images.reshape(10000,28,28,1)

In [415]:
test_images_enhanced.shape

(10000, 28, 28, 1)

## Prepareer de labels

**OPDRACHT**: introduceer "one-hot encoding" voor de labels (zowel train set als de test set)

In [416]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [417]:
train_labels_encoded = to_categorical(train_labels)
test_labels_encoded = to_categorical(test_labels)

In [418]:
train_labels_encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [419]:
test_labels_encoded

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

## Definieeer netwerk / model

**OPDRACHT**: voeg nog een convolutie laag en nog een volledig verbonden laag toe

In [420]:
cnn = models.Sequential()
cnn.add(Conv2D(filters=256,
                  kernel_size=(3, 3),
                  activation='relu',
                  input_shape=(28,28,1)))
cnn.add(MaxPooling2D())
cnn.add(Conv2D(filters=128,
                  kernel_size=(3, 3),
                  activation='relu'))
cnn.add(Conv2D(filters=64,
                  kernel_size=(3, 3),
                  activation='relu'))
cnn.add(MaxPooling2D())
cnn.add(MaxPooling2D())
cnn.add(Flatten())
cnn.add(Dropout(0.3))
cnn.add(Dense(512,activation='relu'))
cnn.add(Dropout(0.3))
cnn.add(Dense(10, activation ='softmax'))

In [421]:
cnn.summary()

Model: "sequential_21"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_70 (Conv2D)           (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_71 (Conv2D)           (None, 24, 24, 32)        9248      
_________________________________________________________________
batch_normalization_24 (Batc (None, 24, 24, 32)        128       
_________________________________________________________________
dropout_43 (Dropout)         (None, 24, 24, 32)        0         
_________________________________________________________________
conv2d_72 (Conv2D)           (None, 22, 22, 64)        18496     
_________________________________________________________________
conv2d_73 (Conv2D)           (None, 20, 20, 64)        36928     
_________________________________________________________________
batch_normalization_25 (Batc (None, 20, 20, 64)      

In [422]:
cnn.compile(optimizer='adam',
            metrics = ['accuracy'],
            loss = 'categorical_crossentropy')

**OPDRACHT**: meet hoe lang het trainen duurt


In [423]:
import time

start = time.perf_counter()
history_cnn = cnn.fit(train_images_enhanced,
        train_labels_encoded,
        epochs = 10,
        batch_size = 128,
        validation_data = (test_images_enhanced, test_labels_encoded))
end = time.perf_counter()  - start
print(f"Training took {}")

Epoch 1/25
938/938 [==============================] - 19s 20ms/step - loss: 0.4075 - accuracy: 0.9163 - val_loss: 62.8874 - val_accuracy: 0.9468

KeyboardInterrupt: 

**OPDRACHT**: meet hoe lang het testen duurt

In [ ]:
loss, acc = cnn.evaluate(test_images_enhanced,
                         test_labels_encoded)

print(acc)

In [ ]:
plt.plot(history_cnn.history['accuracy'])
plt.plot(history_cnn.history['val_accuracy'])
plt.ylim(0.75,1.0)
plt.show()

**OPDRACHT**: evalueer je resultaten:

* hoe is de nauwkeurigheid?
* is het netwerk onder- of over-trained?
* wat kun je nog doen om de nauwkeurigheid te verhogen?

(noteer de veranderingen die je hebt aangebracht en wat daar de resultaten van zijn)

Wat sowieso duidelijk is dat de modellen het allemaal heel goed doen. In volgorde van performance KNN, NN en dan CNN,
die allemaal ruim boven de 95% scoren. De CNN is hier het beste, met een maximum gehaalde val_acc van 0.9940. Dit kunnen
 we verklaren omdat een CNN in meerdere dimensies kan trainen. Het model is niet per se underfitted of overfitted, maar
 eigenlijk net goed.

Ik heb aardig gespeeld met vershillende hoevelheden neuronen, convolutional layers en dropout. Maar om het verder dan
dit te verbeteren moet er echt gewoon lange tijd geexperimenteerd worden.

**OPDRACHT**: evalueer je resultaten:

vergelijk de resultaten van kNN, NN, en CNN

* wat concludeer je hieruit?
* welke type fouten maken de verschillende classifiers?


